// Generated by the protogen-tool.
// Add your logic code in Handle func.
package knight.gsp;

public class CEnterWorldHandler implements knight.gsp.IProtocolHandle {

    private knight.gsp.protogen.CEnterWorld p;

    @Override
    public void Handle(knight.gsp.account.Account account) {
        //TODO. add your code here
    }

}