// Generated by the protogen-tool.
// Add your logic code in Handle func.
package knight.gsp.item;

public class CUseItemHandler implements knight.gsp.IProtocolHandle {

    private knight.gsp.item.protogen.CUseItem p;

    @Override
    public void Handle(knight.gsp.account.Account account) {
        //TODO. add your code here
    }

}